#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <X11/Xlib.h>
#include <X11/Xresource.h>

#define TERM_COLS 16
#define BG_COLS 2

static char termcols[][8] = { "#45475A", "#F38BA8", "#A6E3A1", "#F9E2AF",
                              "#89B4FA", "#F5C2E7", "#94E2D5", "#BAC2DE",
                              "#585B70", "#F38BA8", "#A6E3A1", "#F9E2AF",
                              "#89B4FA", "#F5C2E7", "#94E2D5", "#A6ADC8" };
static char bgcols[][8]   = { "#1E1E2E", "#313244" };

typedef struct {
	char *name;
	char *dst;
} ResourcePref;

/* Xresources preferences to load at startup */
ResourcePref resources[] = {
	{ "color0",      termcols[0] },
	{ "color1",      termcols[1] },
	{ "color2",      termcols[2] },
	{ "color3",      termcols[3] },
	{ "color4",      termcols[4] },
	{ "color5",      termcols[5] },
	{ "color6",      termcols[6] },
	{ "color7",      termcols[7] },
	{ "color8",      termcols[8] },
	{ "color9",      termcols[9] },
	{ "color10",     termcols[10] },
	{ "color11",     termcols[11] },
	{ "color12",     termcols[12] },
	{ "color13",     termcols[13] },
	{ "color14",     termcols[14] },
	{ "color15",     termcols[15] },
	{ "background0", bgcols[1] },
	{ "background1", bgcols[1] },
};

static void
resourceload(XrmDatabase db, char *name, void *dst)
{
	XrmValue ret;
	char fullname[256];
	char color[8];
	char *type;

	snprintf(fullname, sizeof(fullname), "%s.%s", "dwmblocks", name);
	
	fullname[sizeof(fullname)-1] = '\0';
	if (XrmGetResource(db, fullname, "*", &type, &ret) == 0)
		return;
	if (ret.addr == NULL)
		return;

	strncpy(color, ret.addr, sizeof(color) - 1);
	color[sizeof(color)-1] = '\0';
	strcpy(dst, color);
}

static void
loadxresources(void)
{
	ResourcePref *p;
	XrmDatabase db;
	Display *display;
	char *resm;

	if (!(display = XOpenDisplay(NULL))) {
		perror("XOpenDisplay() failed");
		exit(1);
	}
	if (!(resm = XResourceManagerString(display))) {
		perror("XResourceManagerString() failed");
		exit(1);
	}
	db = XrmGetStringDatabase(resm);
	for (p = resources; p < resources + sizeof(resources) / sizeof(resources[0]); p++)
		resourceload(db, p->name, p->dst);

	XCloseDisplay(display);
}

static void
printheader(char *path) {
	FILE *fp;

	if (!(fp = fopen(path, "w"))) {
		perror("fopen() failed");
		exit(1);
	}

	fprintf(fp, "/* Autogenerated file */\n#ifndef COLORSCHEME\n#define COLORSCHEME\n\n");

	for (unsigned int i = 0; i < TERM_COLS; i++)
		fprintf(fp, "#define CLR_%d \"^c%s^\"\n", i, termcols[i]);

	for (unsigned int i = 0; i < BG_COLS; i++)
		fprintf(fp, "#define BG_%d \"^b%s^\"\n", i, bgcols[i]);

	fprintf(fp, "#define NRM \"^d^\"\n\n#endif /* COLORSCHEME */\n");
	fclose(fp);
}

int
main(int argc, char *argv[])
{
	if (argc != 2) {
		fprintf(stderr, "Invalid number of arguments. Usage: %s path_of_header\n", argv[0]);
		exit(1);
	}

	loadxresources();
	printheader(argv[1]);
	return 0;
}
